from . import chatbot_controller
from . import service_controller
from . import queue_controller
from . import ticket_controller
from . import reservation_controller
from . import rattachement_controller
from . import display_controller
from . import ticket_display_controller
from . import pharmacie_controller
from . import PrescriptionApiController
from . import localisation_controller
from . import mobile_order_controller